# Which script to load from derp.scripts
script: 'Clone'
required: True
class: 'Inferer'
name: 'clone'

# Dataset creation parameters
create:
  data_folders: ['train']
  train_chance: 0.9
  n_perts: 1
  perts:
    shift: 0.2 # meters
    rotate: 5 # degrees
    
# Training related parameters
train:
  prepare:
    - {name: 'colorjitter', brightness: 0.5, contrast: 0.5, saturation: 0.5, hue: 0.1}

# Where to cut out the patch
thumb:
  component: 'camera_front'
  hfov: 75
  vfov: 37.5
  height: 64
  width: 128
  depth: 3
  x: 0
  y: 0.36
  z: -0.23
  pitch: -8.5
  yaw: 0
  roll: 0

# The status we feed into the network
status:
  - {field: 'speed', scale: 1 }

# States we will predict
predict:
  - {field: 'speed', delay: 0.33, scale: 1 }
  - {field: 'steer', delay: 0.33, scale: 1 }
