# Which script to load from derp.scripts
script: 'CloneAdaSpeed'
required: True
class: 'Inferer'
name: 'cloneadaspeed'

# Training related parameters
create:
  data_folders: ['train']
  train_chance: 0.9
  n_perts: 3
  perts:
    shift:
      max: 0.1 # meters
      fudge: 1.0
      timedecay: 1.0
    rotate:
      max: 10 # degrees
      fudge: 0.05
      timedecay: 1.0

# Training related parameters  
training:
  prepare:
    - {name: 'colorjitter', brightness: 0.5, contrast: 0.5, saturation: 0.5, hue: 0.1}

# What we expect for input from the camera
thumb:
  component: 'camera_front'
  hfov: 75
  vfov: 37.5
  height: 64
  width: 128
  depth: 3
  x: 0
  y: 0.36
  z: -0.23
  pitch: -8.5
  yaw: 0
  roll: 0

# The status we feed into the network
status: []

# States we will predict
predict:
  - {field: 'steer', delay: 0.4, scale: 1 }
  - {field: 'steer', delay: 2.4, scale: 1 }
#  - {field: 'shift', scale: 10 }
#  - {field: 'rotate', scale: 0.1 }

# Other parameters that will affect things during autonomous mode
scale: 0.5
power: 2
use_min_for_speed: true
