
components: 
 - name: 'controller_dualshock4'
   required: True
   class: 'Dualshock4'
   deadzone: 4
   speed_elbow: [0.1, 0.8, 0.3]
   steer_normalizer: [0, 1, 2]
   state:
     timeout: 1.0

 - name: 'keyboard'
   required: False
   class: 'Keyboard'
   exact: False

 - name: 'camera_front'
   required: True
   class: 'Camera'
   index: 1
   hfov: 75
   vfov: 56.25
   fps: 60
   height: 480
   width: 640
   depth: 3
   x: 0
   y: 0.36
   z: -0.23 
   pitch: -8.5
   yaw: 0
   roll: 0
   bottom_row_width: 1.07
   bottom_row_z: 0.49
   vehicle_width: 0.3
   state:
     camera_front: null
     timestamp: null

 - name: 'imu_stalk'
   required: False
   class: 'BNO055'
   busnum: 0
   state:
     quaternion_w: 0.0
     quaternion_x: 0.0
     quaternion_y: 0.0
     quaternion_z: 0.0
     euler_h: 0.0
     euler_r: 0.0
     euler_p: 0.0
     gravity_x: 0.0
     gravity_y: 0.0
     gravity_z: 0.0
     gravity_x: 0.0
     gravity_y: 0.0
     gravity_z: 0.0     
     temp: 0.0

 - name: 'servo_speed'
   required: True
   class: 'UsbServo'
   index: 1
   act_state: 'speed'
   min_value: -0.95
   max_value: 0.95
   state:
     speed: 0.0
  
 - name: 'servo_steer'
   required: True
   class: 'UsbServo'
   index: 0
   act_state: 'steer'
   min_value: -0.95
   max_value: 0.95
   state:
     steer: 0.0
     steer_offset: 0.0
