
no_cuda: False

components:
  - path: "joystick/dualshock4.yaml"
  - path: "input/keyboard.yaml"
  - path: "camera/OV2710_100fov_1920x1080.yaml"
    name: 'camera_front'
    x: -0.23 # meters forward from front axle
    y:  0.00 # meters left from center of vehicle. Assume zero for now
    z:  0.36 # meters up from floor
    roll:   0.0 # degrees left tilt. Assume zero for now
    pitch: -8.5 # degrees incline
    yaw:    0.0 # degrees left turn. Assume zero for now
    bottom_row_width: 1.07 # width in meters of bottom pixel row
    bottom_row_x:     0.49 # distance in meters of bottom pixel row from camera
    vehicle_width:    0.30 # width of car in meters
  - path: "imu/bno055.yaml"
  - path: "servo/micromaestro_speed_3785.yaml"
  - path: "servo/micromaestro_steer_2075.yaml"
  - path: "inference/clone.yaml"
    camera_name: 'camera_front'
