
no_cuda: False
model_dir: Null

components:
  - path: "joystick/dualshock4.yaml"
  - path: "input/keyboard.yaml"
  - path: "camera/OV2710_100fov_1920x1080.yaml"
    name: "camera_front"
    x: -0.23 # meters forward from front axle
    y:  0.00 # meters left from center of vehicle. Assume zero for now
    z:  0.36 # meters up from floor
    roll:   0.0 # degrees left tilt. Assume zero for now
    pitch: -8.5 # degrees incline
    yaw:    0.0 # degrees left turn. Assume zero for now
  - path: "imu/bno055.yaml"
    name: "imu_stalk"
  - path: "servo/micromaestro_speed_3785.yaml"
    state:
      offset_speed: 0.2 # start at a reasonable high speed
  - path: "servo/micromaestro_steer_2075.yaml"
    state:
      offset_steer: 0.0 # assume no steering bias
  - path: "inference/clone_adaspeed.yaml"
    camera_name: "camera_front"
    create:	 
      data_folders: ['train']
      train_chance: 0.9
  n_perts: 3
  perts:
    shift:
      max: 0.1 # meters
      fudge: 0.5
      timedecay: 1.0
    rotate:
      max: 5 # degrees
      fudge: 0.02
      timedecay: 1.0    
