#Directory Assitance:
dir:
    train_data: line_train_data/training
    val_data: line_train_data/validation
    model: 'DRP_MODEL'
    model_name: 'line_007'
    validation: 'line_validation'

line:
    #line attributes
    n_lines: 3
    n_points: 3
    n_dimensions: 2

    #cropped view characteristics
    cropped_width: 640
    cropped_height: 160

    #Model input characteristics
    n_channels: 3
    input_width: 128 # visible space
    input_height: 32 

    n_segments: 32