#Directory Assitance:
dir:
    train_data: line_train_data
    model: 'DRP_MODEL'
    model_name: 'line_002'
    validation: 'line_validation'

line:
    n_lines: 3
    n_points: 3
    n_dimensions: 2

    n_channels: 1
    view_width: 192 # visible space
    view_height: 32 

    n_segments: 20