#Directory Assitance:
dir:
    train_data: line_train_data
    model: 'DRP_MODEL'
    model_name: 'line_003'
    validation: 'line_validation'

line:
    #line attributes
    n_lines: 3
    n_points: 3
    n_dimensions: 2

    #cropped view characteristics
    cropped_width: 1920
    cropped_height: 320

    #Model input characteristics
    n_channels: 1
    input_width: 192 # visible space
    input_height: 32 

    n_segments: 20